### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by cobirnm** [CyberIN-pl/Orno-OR-WE-526#1]
Hello,

I'm trying to setup an orno OR-WE-526 and using orno software I'm unable to set the tarrif and rates.
Sorry and I know this is out of the scope of your project but your repository was the only one I found using this meter. Could you be so kind and give me some pointers on how to set up the tarrifis?

Thank you in advance.

P.S. This is the software that I', using:

![image](https://github.com/CyberIN-pl/Orno-OR-WE-526/assets/45829329/ba6564f0-69a9-486d-b31e-0bb0a806e8c7)

**Comment by Controli-pl** [comment]
Hello,
Unfortunately, I have never had any experience with orno software.
The first thing that comes to my mind is a connection problem.
Are you able to read any values from the meter, for example voltage?
I looked in the manual but didn't find anything useful there.
What caught my eye was the default counter address "001" - have you tried entering it in this format?
I don't know if it will help, but you can try.

Good luck ;-)
P

**Comment by cobirnm** [comment]
> Hello, Unfortunately, I have never had any experience with orno software. The first thing that comes to my mind is a connection problem. Are you able to read any values from the meter, for example voltage? I looked in the manual but didn't find anything useful there. What caught my eye was the default counter address "001" - have you tried entering it in this format? I don't know if it will help, but you can try.
> 
> Good luck ;-) P

Thank you for your reply. I can in fact read all the data using orno software. I can even write data like date and time. Just in the time table that I'm unable to write. 
Please close the issue, and again thank you for answering. It was worth the try.
Right now my hopes rely on Orno support.
